# Generated by Django 5.0.3 on 2024-03-25 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagementSystem', '0002_task_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-create']},
        ),
    ]
