# Generated by Django 5.0.3 on 2024-03-25 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TaskManagementSystem', '0003_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['complete']},
        ),
    ]
